### ISSUE TITLE
ticdc v6.5.3 upgrade to v6.5.6, `case-sensitive` should change value to `false` or not?

### ISSUE THREAD

**Issue by River2000i** [pingcap/tiflow#10788]
### What did you do?

1. tiup deploy v6.5.3 cluster with cdc
2. create changfeed with default config and do not set any config explicitly
3. upgrade to v6.5.6
4. check changefeed config

### What did you expect to see?
the config change default value since 
v6.5.6: https://docs.pingcap.com/tidb/v6.5/ticdc-changefeed-config#changefeed-configuration-parameters
v7.1.3: https://docs.pingcap.com/tidb/v7.1/ticdc-changefeed-config#changefeed-configuration-parameters
v7.5.0: https://docs.pingcap.com/tidb/stable/ticdc-changefeed-config#changefeed-configuration-parameters
![image](https://github.com/pingcap/tiflow/assets/96465211/7d3c29a9-03df-4b70-b873-0c60ac008c16)

`case-sensitive` should change to false for the changefeed created before upgrade?

### What did you see instead?
`case-sensitive` config didn't  change after upgrade
![image](https://github.com/pingcap/tiflow/assets/96465211/b6415ca5-25d7-4b7e-b505-adb0cd4e144a)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by River2000i** [comment]
close since it's default behavior

**Comment by River2000i** [comment]
@benmeadowcroft ptal~

**Comment by benmeadowcroft** [comment]
> @benmeadowcroft ptal~

Will do

**Comment by benmeadowcroft** [comment]
With respect to the question on whether the configuration of the changefeed should have been automatically modified during the upgrade due to the change in the default value my response is that it should not be automatically changed.

There are two key reasons for this determination:

First, changing behavior on upgrade should be avoided unless absolutely unavoidable. If we change behavior on upgrade it adds an unplanned operational burden to customers at the time of upgrade. Particularly if this would impact a large number of changefeeds.

Second, the changefeed configuration file is an option passed from the client and is not a persistent server side file as say the TiCDC server configuration file. As such the proper time to apply (or update) defaults is when the changefeed is created or updated. This also ensures that any change in behavior is closely linked to a specific operational action that can be expected to make such a change. If there is unexpected behavior as a result of the changefeed creation or modification (unexpected due to not reading the release notes for example), then the operator who made that change has a better context and opportunity to remediate the issue right away compared to an operator performing an upgrade.

In reviewing the documentation, I do note that this item was called out in the [6.5.6 release notes](https://github.com/pingcap/docs/blob/release-6.5/releases/release-6.5.6.md?plain=1#L18):
> After further testing, the default value of the TiCDC Changefeed configuration item [`case-sensitive`](/ticdc/ticdc-changefeed-config.md) is changed from `true` to `false`. This means that by default, table and database names in the TiCDC configuration file are case-insensitive [#10047](https://github.com/pingcap/tiflow/issues/10047) @[sdojjy](https://github.com/sdojjy)

Given this I am not sure if there is any change needed to address this issue. The behavior is as expected, and is documented in the release notes.

**Comment by asddongmen** [comment]
Close since there no more update.
