### ISSUE TITLE
changefeed lag reached 556s when inject network partition between one of ticdc and pd leader last for 10mins

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#10849]
### What did you do?

1、create changefeed
2、run sysbench
3、inject network partition between one of ticdc and pd leader last for 10mins

### What did you see instead?

changefeed lag reached 556s

![image](https://github.com/pingcap/tiflow/assets/84712107/876b7bb5-e404-4c6f-a707-2c33da99ba48)

### Versions of the cluster

./cdc version
 Release Version: v8.0.0
Git Commit Hash: ba58ef95943300b022ef4673ddd5f0b2b58a412d
Git Branch: HEAD
UTC Build Time: 2024-03-19 08:07:03
Go Version: go version go

**Comment by asddongmen** [comment]
close by #10881

**Comment by asddongmen** [comment]
Based on the existing design, the delay of cdc cannot be guaranteed in this situation.

**Comment by asddongmen** [comment]
TiCDC communicates with PD to obtain the latest region information from upstream TiKV in order to establish a data capture stream for the regions. If a cdc server experiences a network partition with the PD leader, it cannot receive this information, and as a result, it cannot establish the stream. This leads to an increase in changefeed lag.
