### ISSUE TITLE
changefeed resolved ts can not go on after restart all pd、tikv and tidb

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#10955]
### What did you do?

1、create changefeed
2、run sysbench
3、kill all pd、tikv and tidb

### What did you expect to see?

after pod start，changefeed status can recover and resolved ts can go on

### What did you see instead?

after pod start，changefeed resolved ts can not go on  and changefeed status was abnormal
![img_v3_02a8_eac7f1ef-71a7-408f-a0ff-edfa538dad9g](https://github.com/pingcap/tiflow/assets/84712107/2b04eb87-6ae8-431d-b87f-6186154298f0)
![img_v3_02a8_07e73f67-6672-48bb-9508-5d33d5c659fg](https://github.com/pingcap/tiflow/assets/84712107/a82ed271-d93e-41f0-8ce8-3c078fd4147d)

### Versions of the cluster

./cdc version
 Release Version: v8.2.0-alpha
Git Commit Hash: fe19cd9c9e4044d3ae70b32134ce521e39a3feb2
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-04-22 11:37:02
Go Version: go version go1.21.6 linux/amd64
Failpoint Build: false

**Comment by CharlesCheung96** [comment]
The root cause of this issue is [PR #10928](https://github.com/pingcap/tiflow/pull/10928/files#diff-55a9a4424fd834ec23f010504e478b5b98b36ad6c267c3807dbb36bd433fd3a5R503):
1. When initialization fails, the processor only reports warn, and then every time it ticks, it enters the TryInitialize logic and returns the same error, leading to an endless loop in processor goroutine.
https://github.com/pingcap/tiflow/blob/72646f6825a7288131b553f4cb67b9ea3b0662b4/cdc/async/async_initializer.go#L80-L82
2. For the owner goroutine, it will [advance the checkpointTsAdvanced in each tick](https://github.com/pingcap/tiflow/blob/72646f6825a7288131b553f4cb67b9ea3b0662b4/cdc/owner/feed_state_manager.go#L155-L157) because the resolvedTs is stuck. Therefore, changefeed will [not be set to failed state]() even if checkpointTs does not advance for a long time.
https://github.com/pingcap/tiflow/blob/72646f6825a7288131b553f4cb67b9ea3b0662b4/cdc/owner/feed_state_manager.go#L455-L472
