### ISSUE TITLE
TiCDC OOM（Kafka Sink ）

### ISSUE THREAD

**Issue by Bowen-Tang** [pingcap/tiflow#5163]
### What did you do?

The operations on the application side is not yet identified. The default transaction size is 100MB, and the downstream is Kafka. Meanwhile, the changefeed is configured to synchronize single table.

The attachment contains golang heap and table schema.
[cdcoom.zip](https://github.com/pingcap/tiflow/files/8480267/cdcoom.zip)

### What did you see instead?

No matter the VM is configured with 32GB or 64 GB memory, CDC drains the memory entirely.

### Versions of the cluster

V5.3.1

**Comment by zhaoxinyu** [comment]
This issue is under investigation.

**Comment by CharlesCheung96** [comment]
@Bowen-Tang  Can you provide the monitoring data and detailed version information of cdc?

**Comment by CharlesCheung96** [comment]
![image](https://user-images.githubusercontent.com/61726649/172827251-1314d51f-4c01-48f3-9f3d-39b2350a270e.png)
@Bowen-Tang  According to Puller's monitoring, the workload of this CDC node is relatively abnormal, which is far beyond the throughput capacity of the downstream under normal circumstances. Therefore, we highly suspect that inconsistent upstream and downstream throughput will cause data accumulation in memory, which will eventually lead to OOM. 

This [pr](
https://github.com/pingcap/tiflow/pull/5712) alleviates the OOM problem caused by upstream and downstream throughput to a certain extent, so we temporarily closed the issue. If similar problems occur again, feel free to reopen it.
