### ISSUE TITLE
skip unexpected var in statusVarsToKV and check error first when using result kv

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tiflow#6121]
### Is your feature request related to a problem?

no

### Describe the feature you'd like

right now we take unexpected(undocumented) vars as error, but we don't depends on it anyway, warn and skip it is better
https://github.com/pingcap/tiflow/blob/3534963668aa54d010709c3ea45db6b2e58327c7/dm/pkg/binlog/event/util.go#L526

then in code below and other code uses `statusVarsToKV`, we can check error first to avoid anti-pattern code. 
https://github.com/pingcap/tiflow/blob/3534963668aa54d010709c3ea45db6b2e58327c7/dm/pkg/binlog/event/util.go#L335-L344

**Comment by lance6716** [comment]
@lyzx2001 

To me, the fixing change for this issue is:

- `statusVarsToKV` will not return `error`. If it meet errors like unrecognized key or EOF, it can log the error using `DPanic` level and return the half-finished map. So even when it meets EOF which means status var is malformed, caller still have the chance to work properly if the wanted key has been parsed. And in CI `DPanic` level will let CI fail.
- callers of `statusVarsToKV` can then decide the behaviour when it doesn't find the key.

#6119 is small, you can add the fix in it, or you can open a new PR.

**Comment by D3Hunter** [comment]
for `EOF` and `duplicate key` which should not happen for normal binlog stream and dummy event, we can return error and let syncer handle it.

**Comment by D3Hunter** [comment]
> statusVarsToKV will not return error.

you are right. previous i thought we can `skip` and continue parsing, but we cannot.

add some comment might be enough. issue closed
