### ISSUE TITLE
DM and TiDB has different behaviour for FK

### ISSUE THREAD

**Issue by circle006** [pingcap/tiflow#6247]
### Is your feature request related to a problem? Please describe

DM 同步时出现报错：外键约束中被关联的表没有创建
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/76728409/178215312-3b4e3b4c-5c60-43aa-ba7a-f39b8e110b4f.png">
TiDB 对于外键约束行为如下，会跳过检查：
<img width="576" alt="image" src="https://user-images.githubusercontent.com/76728409/178215829-9fa188cb-73ab-4c9c-95d0-28f6b37f7b33.png">

### Describe the feature you'd like

DM 与 TiDB 的行为保持一致，都可以跳过外键约束的检查

**Comment by lance6716** [comment]
It is caused by DM wants to handle statements that refer another table, like CREATE TABLE ... LIKE . For these statements, DM will fetch the refered tables from downstream. DM uses the AST visitor below to get all table names in a statement and will fetch tables according to the table names.

https://github.com/pingcap/tiflow/blob/350821b95314a149850a3912f2424bbac2b01f5a/dm/pkg/parser/common.go#L68

We should skip the table name under FOREIGN KEY, TiDB don't need it.
