### ISSUE TITLE
Engine supports using s3 to store file resources

### ISSUE THREAD

**Issue by liuzix** [pingcap/tiflow#7114]
- [ ] Implement `FileManager` for s3. https://github.com/pingcap/tiflow/pull/7034
- [ ] Refactor existing code and integration the `FileManager` into existing code #7127
- [ ] Integration and system tests.

**Comment by CharlesCheung96** [comment]
TODO:

- [ ] Figure out the root cause of performance rollback in [integration tests](https://ci2.pingcap.net/blue/organizations/jenkins/engine_ghpr_integration_test/detail/engine_ghpr_integration_test/1240/pipeline/)
- [ ] Implements remove resource interface for framework
- [ ] Always create a dump task with resource constraints
